### ISSUE TITLE
Broken link to correspondance-code-insee-code-postal.csv

### ISSUE THREAD

**Issue by gildasch** [macbuse/Elections-in-France#1]
The data.gouv.fr page you're linking to only gives access to a simplified document. The `geo_shape` for example is not included.

Thanks

**Comment by macbuse** [comment]
I updated the repo. Here is the good link.

- [Postal codes/GPS data are available here](https://public.opendatasoft.com/explore/dataset/correspondance-code-insee-code-postal/export/)
various options for download I picked 
**comma separated values** file.

**Comment by gildasch** [comment]
Thanks!
